name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build (PyInstaller)
        working-directory: src
        run: |
          pyinstaller --clean --onefile --noconsole --name ChromeBookmarksSorterGUI chrome_bookmarks_sorter_gui.pyw

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChromeBookmarksSorterGUI
          path: src/dist/ChromeBookmarksSorterGUI.exe

